# SPDX-License-Identifier: Apache-2.0
# Customer application manifest. RZI is consumed as an independent west project;
# the default USP backend dependencies are imported from the RZI manifest.

manifest:
  version: "1.2"

  self:
    path: app

  remotes:
    - name: zephyrproject-rtos
      url-base: https://github.com/zephyrproject-rtos
    - name: rzi-origin
      url-base: https://github.com/DanielCao0

  projects:
    - name: zephyr
      remote: zephyrproject-rtos
      revision: 161f758ba363ec90cd9b727a5d82e6c86efa85ad
      import: true

    - name: rzi
      repo-path: RZI
      remote: rzi-origin
      revision: main
      import: true
