#!/usr/bin/env python3
"""Scan patches/**/*.patch and regenerate patches.yml with west SHA-256 values.

Run from the repository root:

  python3 scripts/generate-patch-manifest.py

Existing comments, author, email, and date fields are retained by path.
"""
from __future__ import annotations

import argparse
import hashlib
import re
from datetime import date
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parents[1]
PATCH_ROOT = REPO_ROOT / "zephyr" / "patches"


def west_sha256(path: Path) -> str:
    with open(path, encoding="utf-8", newline=None) as fp:
        return hashlib.sha256(fp.read().encode("utf-8")).hexdigest()


def load_old(yml: Path) -> dict[str, dict]:
    """Load hand-maintained fields from existing entries, indexed by path."""
    if not yml.is_file():
        return {}
    text = yml.read_text(encoding="utf-8")
    old: dict[str, dict] = {}
    current: dict | None = None
    in_comments = False
    comment_lines: list[str] = []
    for line in text.splitlines():
        m = re.match(r"  - path: (\S+)", line)
        if m:
            if current:
                if comment_lines:
                    current["comments"] = "\n".join(comment_lines).rstrip()
                old[current["path"]] = current
            current = {"path": m.group(1)}
            in_comments = False
            comment_lines = []
            continue
        if current is None:
            continue
        if in_comments:
            if line.startswith("      "):
                comment_lines.append(line[6:])
                continue
            in_comments = False
        km = re.match(r"    (author|email|date|upstreamable): (.+)$", line)
        if km:
            current[km.group(1)] = km.group(2)
        elif re.match(r"    comments: \|", line):
            in_comments = True
    if current:
        if comment_lines:
            current["comments"] = "\n".join(comment_lines).rstrip()
        old[current["path"]] = current
    return old


def yaml_comment_block(text: str) -> list[str]:
    return ["    comments: |"] + [f"      {ln}" if ln else "      " for ln in text.split("\n")]


def main() -> None:
    p = argparse.ArgumentParser(description="Regenerate patches.yml from patches/")
    p.add_argument("-o", "--output", type=Path, default=REPO_ROOT / "zephyr" / "patches.yml")
    p.add_argument("--author", default="rzi")
    p.add_argument("--email", default="patches@rzi.local")
    args = p.parse_args()

    files = sorted(PATCH_ROOT.rglob("*.patch"))
    if not files:
        raise SystemExit(f"no .patch under {PATCH_ROOT}")

    old = load_old(args.output)

    lines = [
        "# Generated by scripts/generate-patch-manifest.py for use by west patch.",
        "# Documentation: doc/west-patch.md",
        "checkout-command: git checkout .",
        'clean-command: ""',
        "",
        "patches:",
    ]
    for f in files:
        rel = f.relative_to(PATCH_ROOT).as_posix()
        module = rel.split("/", 1)[0]
        prev = old.get(rel, {})
        stamp = prev.get("date") or date.fromtimestamp(f.stat().st_mtime).isoformat()
        comments = prev.get("comments") or f"Automatically registered from {rel}; update this comment."
        lines += [
            f"  - path: {rel}",
            f"    sha256sum: {west_sha256(f)}",
            f"    module: {module}",
            f"    author: {prev.get('author', args.author)}",
            f"    email: {prev.get('email', args.email)}",
            f"    date: {stamp}",
            f"    upstreamable: {prev.get('upstreamable', 'true')}",
            "    apply-command: git apply",
            *yaml_comment_block(comments),
            "",
        ]

    args.output.write_text("\n".join(lines).rstrip() + "\n", encoding="utf-8")
    print(f"wrote {args.output} ({len(files)} patches)")


if __name__ == "__main__":
    main()
